auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Bill Page 
url: http://billsmiless.github.io
feed: /atom.xml
author_info: <a href="http://billsmiless.github.io/">billsmiless</a>
